eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8030

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'

      # Consumer group for addToCart
      addToCart:
        group-id: addToCart
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      # Consumer group for removeFromCart
      removeFromCart:
        group-id: removeFromCart
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.stringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer

  application:
    name: session-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    cassandra:
      keyspace-name: store
      contact-points: localhost
      port: 7002
      local-datacenter: datacenter1
